# Generated by Django 3.0.7 on 2020-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_password',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
